services:
  db:
    image: postgres:16.2-alpine
    container_name: locstique_db
    environment:
      POSTGRES_DB: locstique
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: locstique_adminer
    ports:
      - "5433:5432"
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - locstique_network

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/locstique
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: locstique_adminer
    volumes:
      - locstique_network

volumes:
  db_data:

networks:
  locstique_network:
    external: true
