spring:
  application:
    name: locstique
  datasource:
    url: jdbc:postgresql://localhost:5433/locstique
    username: admin
    password: locstique_adminer
    driver-class-name: org.postgresql.Driver

    jpa:
      hibernate:
        ddl-auto: none  # or "validate", "create", "create-drop", "none"
      show-sql: true
      database-platform: org.hibernate.dialect.PostgreSQLDialect